[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend_fastapi"

[services.variables]
PORT = "8000"
HOST = "0.0.0.0"
ENVIRONMENT = "production"

[[services]]
name = "frontend"
source = "frontend_nextjs"

[services.variables]
NODE_ENV = "production"
